config/routes.rb
Propertymanager::Application.routes.draw do
  
  resources :payments

  resources :roles

  resources :user_sessions

  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties

end

app/models/repair_request.rb
class RepairRequest < ActiveRecord::Base
  attr_accessible :close_date, :open_date, :request_details, :request_response
  
  belongs_to :submitter, :class_name => 'User', :foreign_key => 'submitter_id'
  belongs_to :responder, :class_name => 'User', :foreign_key => 'responder_id'

end

app/controllers/repair_requests_controller.rb
class RepairRequestsController < ApplicationController
  # GET /repair_requests
  # GET /repair_requests.json
  def index
    if current_user.has_role? :manager
      @repair_requests = RepairRequest.all
    else
      @repair_requests = RepairRequest.where(:submitter_id => current_user)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repair_requests }
    end
  end

  # GET /repair_requests/1
  # GET /repair_requests/1.json
  def show
    @repair_request = RepairRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repair_request }
    end
  end

  # GET /repair_requests/new
  # GET /repair_requests/new.json
  def new
    @repair_request = RepairRequest.new
    
    logger.debug "!!!!!In RepairRequests # new"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repair_request }
    end
  end

  # GET /repair_requests/1/edit
  def edit
    @repair_request = RepairRequest.find(params[:id])
  end

  # POST /repair_requests
  # POST /repair_requests.json
  def create
    @repair_request = RepairRequest.new(params[:repair_request])
    
    @repair_request.submitter = current_user
    
    respond_to do |format|
      if @repair_request.save
        format.html { redirect_to @repair_request, notice: 'Repair request was successfully created.' }
        format.json { render json: @repair_request, status: :created, location: @repair_request }
      else
        format.html { render action: "new" }
        format.json { render json: @repair_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repair_requests/1
  # PUT /repair_requests/1.json
  def update
    @repair_request = RepairRequest.find(params[:id])
    
    # check to see if the updater is the original submitter or if it's a responder
    if @repair_request.submitter != current_user
      @repair_request.responder = current_user
    end

    respond_to do |format|
      if @repair_request.update_attributes(params[:repair_request])
        format.html { redirect_to @repair_request, notice: 'Repair request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repair_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_requests/1
  # DELETE /repair_requests/1.json
  def destroy
    @repair_request = RepairRequest.find(params[:id])
    @repair_request.destroy

    respond_to do |format|
      format.html { redirect_to repair_requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/repair_requests_helper.rb
module RepairRequestsHelper
end

app/views/repair_requests/_form.html.erb
<%= form_for(@repair_request) do |f| %>
  <% if @repair_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair_request.errors.count, "error") %> prohibited this repair_request from being saved:</h2>

      <ul>
      <% @repair_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if current_user && (current_user.has_role? :manager) %>
	  <div class="field">
	    <%= f.label :open_date %><br />
	    <%= f.date_select :open_date, :disabled => true %>
	  </div>
  <% elsif current_user.has_role? :renter %>
	  <div class="field">
	    <%= f.label :open_date %><br />
	    <%= f.date_select :open_date %>
	  </div>
  <% end %>
  
  
  <% if current_user && (current_user.has_role? :manager) %>
	  <div class="field">
	    <%= f.label :close_date %><br />
	    <%= f.date_select :close_date %>
	  </div>
  <% elsif current_user.has_role? :renter %>
	  <div class="field">
	    <%= f.label :close_date %><br />
	    <%= f.date_select :close_date, :disabled => true %>
	  </div>
  <% end %>
  
  
  
  <% if current_user && (current_user.has_role? :manager) %>
	  <div class="field">
	    	<%= f.label :request_details %><br />
	    	<%= f.text_area :request_details, :disabled => true %>
	  </div>  
  <% elsif current_user.has_role? :renter %>
		<div class="field">
			<%= f.label :request_details %><br />
			<%= f.text_area :request_details %>
		</div>
  <% end %>


  
  <% if current_user && (current_user.has_role? :manager) %>
	  <div class="field">
    	<%= f.label :request_response %><br />
    	<%= f.text_area :request_response %>
	  </div>
  <% elsif current_user.has_role? :renter %>
	  <div class="field">
    	<%= f.label :request_response %><br />
    	<%= f.text_area :request_response, :disabled => true %>
	  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repair_requests/edit.html.erb
<h1>Editing repair_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair_request %> |
<%= link_to 'Back', repair_requests_path %>

app/views/repair_requests/index.html.erb
<h1>Listing repair_requests</h1>

<table>
  <tr>
    <th>Open date</th>
    <th>Close date</th>
    <th>Request details</th>
    <th>Request response</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repair_requests.each do |repair_request| %>
  <tr>
    <td><%= repair_request.open_date %></td>
    <td><%= repair_request.close_date %></td>
    <td><%= repair_request.request_details %></td>
    <td><%= repair_request.request_response %></td>
    <td><%= link_to 'Show', repair_request %></td>
    <td><%= link_to 'Edit', edit_repair_request_path(repair_request) %></td>
    <td><%= link_to 'Destroy', repair_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repair request', new_repair_request_path %>

app/views/repair_requests/new.html.erb
<h1>New repair_request</h1>

<%= render 'form' %>

<%= link_to 'Back', repair_requests_path %>

app/views/repair_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Open date:</b>
  <%= @repair_request.open_date %>
</p>

<p>
  <b>Close date:</b>
  <%= @repair_request.close_date %>
</p>

<p>
  <b>Request details:</b>
  <%= @repair_request.request_details %>
</p>

<p>
  <b>Request response:</b>
  <%= @repair_request.request_response %>
</p>


<%= link_to 'Edit', edit_repair_request_path(@repair_request) %> |
<%= link_to 'Back', repair_requests_path %>