config/routes.rb
Propertymanager::Application.routes.draw do
  
  resources :payments

  resources :roles

  resources :user_sessions

  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :amount, :card_expires_on, :first_name, :ip_address, :last_name, :card_number
  attr_accessor :card_number
  
  validates :amount, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :card_number, :presence => true
  
  validate :validate_card, :on => :create
  
  belongs_to :user
  belongs_to :lease
  
  def make_transaction
    response = GATEWAY.purchase((amount*100), credit_card)
    Rails.logger.warn "!!!!!!!!!!#{response.message}"
    response.success?
  end
  
  
    private
  
  
  
  def credit_card
  @credit_card = ActiveMerchant::Billing::CreditCard.new({
   :first_name => first_name,
   :last_name  => last_name,
   :number     => card_number,
   :month      => card_expires_on.month,
   :year       => card_expires_on.year,
   :verification_value => '999'
})
  end
  
  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        error.add_to_base_message
      end
    end
  end
  
  
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index


    if current_user.has_role? :manager
      @payments = Payment.all
    else
      @payments = current_user.lease.payments
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])
    @payment.ip_address = request.remote_ip
    @payment.user = current_user
    @payment.lease = current_user.lease

Rails.logger.warn '-'*40
Rails.logger.warn @payment.inspect

    respond_to do |format|
      if @payment.save
        if @payment.make_transaction
          format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
          format.json { render json: @payment, status: :created, location: @payment }
        else
          @payment.destroy
          format.html { render action: "failed" }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount, :value => @user.lease.rent %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, :value => @user.username  %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :value => @user.username  %>
  </div>
  <div class="field">
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year) + 10, :add_month_numbers => true %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/failed.html.erb
PAYMENT FAILED

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Card expires on</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Ip address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.amount %></td>
    <td><%= payment.card_expires_on %></td>
    <td><%= payment.first_name %></td>
    <td><%= payment.last_name %></td>
    <td><%= payment.ip_address %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>

<p>
  <b>Card expires on:</b>
  <%= @payment.card_expires_on %>
</p>

<p>
  <b>First name:</b>
  <%= @payment.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @payment.last_name %>
</p>

<p>
  <b>Ip address:</b>
  <%= @payment.ip_address %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>