config/routes.rb
Propertymanager::Application.routes.draw do
  
  resources :payments

  resources :roles

  resources :user_sessions

  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :square_feet, :property_id
  
  belongs_to :property
  has_many :leases
  
    def full_title
    "#{name}: #{property.name}"
  end
  
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :property %><br />
    <%= f.collection_select :property_id, Property.all.collect, :id, :name, :prompt => "Select a property" %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :square_feet %><br />
    <%= f.number_field :square_feet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Square feet</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.full_title %></td>
    <td><%= unit.square_feet %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unit.name %>
</p>

<p>
  <b>Square feet:</b>
  <%= @unit.square_feet %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>