config/routes.rb
Propertymanager::Application.routes.draw do
  
  resources :payments

  resources :roles

  resources :user_sessions

  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties

end

app/views/layouts/application.html.erb
<!-- This HTML file is from the "Pocketing" template found at http://www.freecsstemplates.org -->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Pocketing 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130128

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Property Manager</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href='http://fonts.googleapis.com/css?family=Archivo+Narrow:400,700|Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header" class="container">
			<div id="logo">
				<h1><a href="#">Property Mgmt.</a></h1>
			</div>
			<div id="menu">
				<ul>
					<li class="active"><%= link_to "Home", root_url %></li>
					
					<% if current_user %>
						<li><%= link_to "Rent Payments", payments_path %></li>
						<li><%= link_to "Repair Requests", repair_requests_path %></li>
						<li><%= link_to "Leases", leases_path %></li>
						
					     <% if current_user.has_role? :manager %> 		
							  <li><%= link_to "Properties", properties_path %></li>
							  <li><%= link_to "Units", units_path %></li>
					     <% end %>
					     
					     <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
					     <li><%= link_to "Logout", logout_path %></li>	
					<% else %>	
					        <li><%= link_to "Register", new_user_path %></li>
					        <li><%= link_to "Login", login_path %></li>
					<% end %>

			</div>
		</div>
	</div>
	<div id="page" class="container">
		<div id="content">
			<div id="box1">

			    <% if flash[:error] %>
			        <div id='error'><h2><%=h flash[:error] %></h2></div>
			    <% end %>
			    
				<%= yield %>
			</div>
			<!--
			<div>
				<ul class="style1">
					<li class="first">
						<h3><em><img src="images/img02.jpg" alt="" width="130" height="130" class="alignleft border" /></em>Lorem ipsum dolor interdum</h3>
						<p>Ut vel nisl tristique justo ornare iaculis. Suspendisse suscipit, orci ac interdum viverra, nulla orci facilisis mi, a ultrices mi lectus vitae felis. Morbi suscipit adipiscing orci et blandit. Morbi a nulla ut tellus blandit placerat a quis eros.</p>
						<p><a href="#" class="button-style">Read More</a></p>
					</li>
					<li>
						<h3><em><img src="images/img03.jpg" alt="" width="130" height="130" class="alignleft border" /></em>Magna phasellus etiam ultrices</h3>
						<p>Ut vel nisl tristique justo ornare iaculis. Suspendisse suscipit, orci ac interdum viverra, nulla orci facilisis mi, a ultrices mi lectus vitae felis. Morbi suscipit adipiscing orci et blandit. Morbi a nulla ut tellus blandit placerat a quis eros.</p>
						<p><a href="#" class="button-style">Read More</a></p>
					</li>
				</ul>
			</div>
			-->
		</div>
		<div id="sidebar">
			<h2>Welcome!</h2>
			<ul class="style3">
				<li class="first">
					<% if current_user %>
						<p>Welcome back, <%= current_user.username %>!!</p>
					<% else %>
						<p>Log In using the link above.</p>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
	<div id="footer">
		<p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org">FCT</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
	</div>
</div>
</body>
</html>



</body>
</html>